# Generated by Django 6.0.1 on 2026-01-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('stocks', 'Stocks'), ('bonds', 'Bonds'), ('cryptocurrencies', 'Cryptocurrencies')], default='stocks', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transactionType', models.CharField(choices=[('B', 'buy'), ('S', 'sell')], default='B', max_length=2)),
                ('quantity', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('date', models.DateField(default='2024-01-01')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset')),
            ],
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('ownedAsset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedAssets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
