# Generated by Django 5.0.6 on 2024-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
