# Generated by Django 5.2.10 on 2026-01-25 10:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='base_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='bond_series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='bond_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='face_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='inflation_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='interest_rate_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('variable_wibor', 'Variable WIBOR'), ('indexed_inflation', 'Indexed Inflation')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='wibor_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
