# Dockerfile dla React
FROM node:14 as build

WORKDIR /app

COPY package.json /app/
RUN npm install

COPY . /app/
RUN npm run build

# Przeniesienie skompilowanej aplikacji do katalogu używanego przez Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html