version: '3'
services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    volumes:
      - .:/app
    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - DEBUG=1
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - django
