import "./styles/FundamentalAnalysis.css"
import DividendChart from "./DividendChart"
import RevenueChart from "./RevenueChart"
import React, {useState, useEffect} from "react";
import { FaQuestionCircle } from 'react-icons/fa';
import {Tooltip } from 'react-tooltip';

function formatNumberWithSuffix(number) {
    const suffixes = ["", "K", "M", "B", "T"]; 

    let suffixIndex = 0;
    while (number >= 1000 && suffixIndex < suffixes.length - 1) {
        number /= 1000;
        suffixIndex++;
    }

    return number.toFixed(2) + suffixes[suffixIndex];
}

function FundamentalAnalysis({ticker}){
    let [MarketCap, setMarketCap] = useState(0)
    let [PERatio, setPERatio] = useState(0)
    let [PSRatio, setPSRatio] = useState(0)
    let [EPS, setEPS] = useState(0)
    let [Revenue, setRevenue] = useState([])
    let [Dividends, setDividends] = useState([])

    useEffect(()=>{
        getData()
    },[])
    
    let getData = async () =>{
        let response = await fetch(`/api/fundamental/${ticker}/`)
        let data = await response.json()
        setMarketCap(data['Market Cap'])
        setPSRatio(data['P/S Ratio'])
        setPERatio(data['P/E Ratio'])
        setEPS(data['EPS'])
        setRevenue(data['Revenue History'])
        setDividends(data['Dividend History'])
        console.log('data2:',data)
    }

    return(
            <div className="FundamentalAnalysisContainer">
                <div className="FundamentalContainer" id="MarketCap"> 
                    <h3>Market Capitalization
                    <FaQuestionCircle className="questionCircle" data-tooltip-id="marketCap" data-tooltip-content="The market value of the company. A higher market cap indicates greater stability but lower growth potential, while a lower market cap may suggest higher risk but also greater potential for returns." />
                    <Tooltip id="marketCap" className="custom-tooltip"/>
                    </h3>
                    <h1>{formatNumberWithSuffix(MarketCap)}</h1>
                </div>
                <div className="FundamentalContainer" id="pe"> 
                     <h3>P/E ratio
                    <FaQuestionCircle className="questionCircle" data-tooltip-id="marketCap" data-tooltip-content=" Indicates how much investors are willing to pay for each dollar of the company's earnings. A low P/E might suggest undervaluation, while a high P/E could indicate overvaluation or growth expectations."/>
                     <Tooltip id="marketCap" className="custom-tooltip"/>
                     </h3>
                     <h1>{PERatio.toFixed(2)}x</h1>
                </div>
                <div className="FundamentalContainer" id="ps"> 
                    <h3>P/S ratio
                    <FaQuestionCircle className="questionCircle" data-tooltip-id="marketCap" data-tooltip-content="Shows how much investors are paying for each dollar of the company's revenue. A low P/S might suggest a buying opportunity, while a high P/S reflects optimism about future revenue growth."/>
                    <Tooltip id="marketCap" className="custom-tooltip"/>
                    </h3>
                    <h1>{PSRatio.toFixed(2)}x</h1>
                </div>
                <div className="FundamentalContainer" id="eps">
                    <h3>Earnings Per Share
                    <FaQuestionCircle className="questionCircle" data-tooltip-id="marketCap" data-tooltip-content="The profit allocated to each share of stock. Increasing EPS may indicate strong financial health and potential stock price appreciation."/>
                    <Tooltip id="marketCap" className="custom-tooltip"/>
                    </h3>
                    <h1>{EPS} USD</h1> 
                </div>
                <div className="FundamentalContainer" id="Dividends">
                    <h3>Dividends
                    <FaQuestionCircle className="questionCircle" data-tooltip-id="marketCap" data-tooltip-content="Regular payouts from the company's profits. A high dividend can attract income-seeking investors but may limit the company's ability to reinvest in growth."/>
                    <Tooltip id="marketCap" className="custom-tooltip"/>
                    </h3>
                    <DividendChart data={Dividends}/> 
                </div>
                <div className="FundamentalContainer" id="Earnings"> 
                    <h3>Revenue
                    <FaQuestionCircle className="questionCircle" data-tooltip-id="marketCap" data-tooltip-content="The total income generated by the company. Revenue growth signals increasing demand for the company's products or services, which can be a positive sign for investors."/>
                    <Tooltip id="marketCap" className="custom-tooltip"/>
                    </h3>
                    <RevenueChart data={Revenue}/>
                </div>
            </div>
    )
}

export default FundamentalAnalysis