# Generated by Django 5.2.10 on 2026-02-09 18:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative net cash invested (purchases minus sales) up to this date.', max_digits=15),
        ),
    ]
