# Generated by Django 5.2.10 on 2026-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliosnapshot_total_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency of price when set (e.g. PLN). When null, price is in asset native currency.', max_length=10, null=True),
        ),
    ]
