# Generated by Django 5.2.10 on 2026-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_transactions_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasset',
            name='average_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Average cost per unit of this position, in the given currency.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='userasset',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency of average_purchase_price (e.g. PLN, USD).', max_length=10, null=True),
        ),
    ]
