# Generated by Django 5.2.10 on 2026-04-03 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_economic_calendar_event'),
        ('portfolio', '0004_add_user_asset_average_price_and_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='external_id',
            field=models.CharField(blank=True, help_text='Broker/importer stable id; unique per owner when set.', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('owner', 'external_id'), name='uniq_transactions_owner_external_id'),
        ),
    ]
