# Generated by Django 5.2.10 on 2026-07-07 20:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_transactions_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18),
        ),
    ]
