# Generated by Django 5.2.10 on 2026-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SarimaForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('forecast_date', models.DateField()),
                ('predicted_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol', 'forecast_date'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'forecast_date'), name='unique_sarima_forecast_symbol_date')],
            },
        ),
    ]
