# Generated by Django 5.2.10 on 2026-01-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the economic data measurement', unique=True)),
                ('wibor_3m', models.DecimalField(decimal_places=2, help_text='WIBOR 3M rate in percentage', max_digits=5)),
                ('wibor_6m', models.DecimalField(decimal_places=2, help_text='WIBOR 6M rate in percentage', max_digits=5)),
                ('inflation_cpi', models.DecimalField(decimal_places=2, help_text='CPI inflation rate in percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Economic Data',
                'verbose_name_plural': 'Economic Data',
                'ordering': ['-date'],
            },
        ),
    ]
