# Generated by Django 5.2.10 on 2026-02-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('close', models.DecimalField(decimal_places=4, max_digits=18)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='base.asset')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price History',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='unique_symbol_date')],
            },
        ),
    ]
