# Generated by Django 5.2.10 on 2026-02-14 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_prices', to='base.asset')),
            ],
            options={
                'verbose_name': 'Current Price',
                'verbose_name_plural': 'Current Prices',
                'ordering': ['symbol'],
            },
        ),
    ]
