# Generated by Django 5.2.10 on 2026-02-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_currentprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('data_type', models.CharField(choices=[('basic_info', 'Basic Info'), ('fundamental_analysis', 'Fundamental Analysis'), ('technical_indicators', 'Technical Indicators')], db_index=True, max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Data Cache',
                'verbose_name_plural': 'Stock Data Cache',
                'ordering': ['symbol', 'data_type'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'data_type'), name='unique_stock_data_cache_symbol_type')],
            },
        ),
    ]
