# Generated by Django 5.2.10 on 2026-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_stockdatacache'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('earnings', 'Earnings'), ('ipo', 'IPO')], db_index=True, max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('fiscal_date_ending', models.DateField(blank=True, null=True)),
                ('estimate', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Economic Calendar Event',
                'verbose_name_plural': 'Economic Calendar Events',
                'ordering': ['report_date', 'symbol'],
                'indexes': [models.Index(fields=['event_type', 'report_date'], name='base_econom_event_t_1b5f7c_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'symbol', 'report_date'), name='unique_economic_calendar_event')],
            },
        ),
    ]
